---
# Connecto to GK API
address: <set_UM_Adapter_address_here> # sp.int3.sonata-nfv.eu
port: <set_UM_Adapter_port_here> # 5600
api_ver: /api/v1

# Gatekeeper's User Management endpoints
public_key_path: /public-key
registration_path: /register/service
login_path: /login/service
authorization_path: /authorize

# Component identifiers and credentials
catalogue_client: son-catalogue
catalogue_secret: 1234 # (sample)
repos_client: son-repositories
repos_secret: 1234 # (sample)
